name: main
on:
    pull_request:
        branches: ["main"]

jobs:
    prCheck:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Install
              run: npm i
              
            - name: Expo Preview Action
              uses: expo/expo-preview-action@v1.2.2
